[package]
name = "mafiabot"
version = "0.1.0"
edition = "2021"

[dependencies]
chrono = "0.4.34"
enum-kinds = "0.5.1"
timer = "0.2.0"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html
