[package]
name = "mafia"
version = "0.1.0"
edition = "2021"

[dependencies]
async-trait = "0.1.85"

chrono = { version = "0.4.39", features = ["serde"] }
enum-kinds = "0.5.1"
rand = "0.8.5"
serde = { version = "1.0.217", features = ["derive"] }
statrs = { version = "0.18.0", features = ["rand"] }
thiserror = "2.0.11"
tokio = { version = "1", features = ["full"] }
tracing = "0.1.41"
tracing-test = "0.2.5"
