resp_lib = {
  "VOTE_CHANGE": "[{voter}] retracts vote for [{f_votee}] and votes for [{votee}]",
  "VOTE_RETRACT": "[{voter}] retracted vote for [{f_votee}]",
  "VOTE":       "[{voter}] votes for [{votee}]",
  "VOTE_UPDATE": ", {n_voters}/{thresh} to elect [{votee}]",
  "VOTE_UPDATE_NOKILL": ", {n_voters}/{nokill_thresh} for peace",
  "MTARGET":    "[{actor}] prepares to kill [{target}]",
  "TARGET":     "You have targeted [{target}]",
  "NOTARGET":   "You have decided not to target anyone tonight",
  "REVEAL":     "[{actor}] is {role}",
  "REVEAL_REMINDER": "Remember, [{actor}] is {role}",
  "TIMER_DAY":  "Timer: nokill",
  "TIMER_NIGHT":"Timer: some slept through the night",
  "ELECT":      "[{target}] has been elected to be killed",
  "ELECT_NOKILL":"You have elected not to kill anyone",
  "ELECT_IDIOT": "... They were an IDIOT...",
  "ELECT_DAY"  :" The Day will continue!",
  "ELECT_STUN" :" All who voted for the IDIOT will be stunned tonight.",
  "KILL":       "[{target}] was killed by the mafia!",
  "KILL_FAIL_QUIET":  "It seems nobody died last night...",
  "VENGEANCE":  "[{actor}] takes [{target}] with them",
  "ELIMINATE" : "[{target}] was {role}",
  "ELIMINATE_ANON":"[{target}] has died",
  "CHARGE_DIE_GUARD": "Oh no! Your charge, [{charge}], has died at the hands of [{aggressor}]!",
  "CHARGE_DIE_AGENT": "Congratulations! Your charge, [{charge}], has died at the hands of [{aggressor}]!",
  "SURVIVOR_DIE": "Oh no! You died at the hands of [{aggressor}]! As SURVIVOR, you have lost!",
  "REFOCUS" : "You have been refocused to {new_role}",
  "CHARGE_ASSIGN":"Your charge is [{charge}]",
  "MASON_REVEAL": "The MASONIC ORDER includes:\n{mason_str}",
  "STRIPPED":   "You were distracted...",
  "STUN":       "You are stunned until next morning",
  "STUNNED":    "While stunned you can only target NOTARGET",
  "SAVE":       "[{target}] was saved after being attacked by the mafia!",
  "SAVE_SECRET":"Somebody was saved after being attacked by the mafia!",
  "SAVE_DOC":   "You saved your patient!",
  "SAVE_SELF":  "You were saved!",
  "MILK":       "[{target}] received milk in the night.",
  "NO_MILK_SELF": "Ewww, please don't milk yourself in front of me",
  "INVESTIGATE":"[{target}] is {role}",
  "DAWN":       "Day dawns",
  "DAY":        "Pick someone to elect.",
  "NIGHT":      "Night falls",
  "NIGHT_OPTIONS":"Pick someone to target:\n",
  "DUSK":       "The sky darkens as their reddening eyes observe the crowd...",
  "DUSK_OPTIONS": "Pick someone who voted for you to kill:\n",
  "START":      "Start Game. Everyone is in the MAIN CHAT:",
  "START_MAFIA": "Start Game. You are the Mafia!",
  "WIN":   "{winning_team} won!",
  "IDIOT_WIN": "IDIOT [{idiot}] won!",
  "CONTRACT_WIN":"{role} [{player}] won!",
  "CONTRACT_LOSE":"{role} [{player}] lost!",
  "CHARGE_REVEAL":"Charge: [{charge}]",
  "SHOW_ROLES": "Roles:{start_roles}",

  "INVALID_VOTER": "[{player_id}] cannot vote, not playing",
  "INVALID_VOTEE": "Cannot vote for [{player_id}], they are not playing",
  "INVALID_VOTE_PHASE": "Can only vote during Day",
  "INVALID_TARGET": "Invalid target: {text}",
  "INVALID_TARGETER": "You cannot target if you are not playing",
  "INVALID_TARGET_ROLE": "You cannot target if you don't have a targeting role",
  "INVALID_TARGETED" : "You cannot target [{target_id}] as they are not playing",
  "INVALID_TARGET_PHASE": "Can only target during Night",
  "INVALID_TARGET_STUNNED": "You are stunned. A stunned player can only select NOTARGET",
  "INVALID_ITARGET_PHASE": "Can only take revenge during Dusk",
  "INVALID_ITARGET_PLAYER": "You are not the one who needs vengeance",
  "INVALID_ITARGETED": "Could not target that player as they didn't vote for you",
  "INVALID_TARGET_MILK_SELF": "Ewww... Please don't milk yourself in front of me...",
  "INVALID_MTARGET": "Invalid target: {text}",
  "INVALID_MTARGET_PLAYER": "You cannot target if you are not playing or do not have a mafia role",
  "INVALID_MTARGET_PHASE": "Can only target during Night",
  "INVALID_REVEAL_PLAYER": "You cannot reveal if you are not playing",
  "INVALID_REVEAL_ROLE": "You cannot reveal if you are not a CELEB",
  "INVALID_REVEAL_PHASE": "Can only reveal during Day",
  "INVALID_ACTION_END": "Game has ended, gg no re",

  "IN": "[{sender_id}] ready to join a Game of at least {min_p} players.",
  "OUT": "Removed [{sender_id}]",
  "OUT_NOT_IN" : "You weren't /in",
  "START_TIMER" : "Game will start in {minutes} min if at least {min_p} players are in. Like this message to join!",
  "START_GAME" : "Starting Game:\n{player_list}",
  "FAILED_START_GAME" : "Failed to start a Game",
  "WATCH_NO_GAMES" : "Failed to watch, no Games",
  "WATCH" : "Watching Game #{g_id}",
  "STATUS_NO_GAMES" : "No Games",
  "LOBBY_GAME_END" : "Game #{g_id} Ended:\n"
}

def get_resp(resp, **locs):
  return resp_lib[resp].format(**locs)
